config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  resources :microposts do
    member do
      get "like" => "microposts#vote" , :defaults => { :format => 'js' }
      get "delete" => "microposts#destroy"
      get "current" => "microposts#show"
    end
    resources :comments, module: :microposts
  end
  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                          as: :link_through
  resources :conversations do
    member do
      get "convo" => "conversations#create"
    end
    resources :messages
  end
  resources :favorite_microposts do
    member do
      get "fav" => "favorite_microposts#create"
      # get "favs" => "favorite_microposts#index"
      get "unfav" => "favorite_microposts#destroy"
    end
    # resources :messages
  end
  get '/favorites', to: 'favorite_microposts#index', as: 'favorites'
  # resources :favorite_microposts, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :post, only: [:create, :destroy]
  resources :microposts, only: [:create, :show, :destroy]
  resources :profilepics, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  get '/search' => 'users#search', :as => 'search_page'
  # match '/microposts/:id', to: 'microposts#destroy', via: 'get'
  # match '/microposts/:id', to: 'microposts#destroy', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/profilepics', to: 'static_pages#profilepic', via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/microposts/:id/like', to: 'microposts#vote', via: 'get', xhr: true



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @users = User.paginate(page: params[:page])
    end
  end
  def profilepic
    if signed_in?
      @profilepic  = current_user.profilepics.build
    end
  end
  def help
  end
  def about
  end
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>
  The Instaclone App is a clone of the functionalities of the original <a href="http://instagram.com/">Instagram App</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  UNDER DEVELOPEMENT
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  UNDER DEVELOPEMENT
</p>

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <div class="span8">
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
      <%= render 'shared/feed' %>
    </div>
    <aside class="span4">
      &nbsp;
      &ensp;
      &emsp;
      &nbsp;
      &ensp;
      &emsp;
      &nbsp;
      &ensp;
      &emsp;
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/suggested_users' %>
      </section>
      <section>
        <%= link_to "About - ",   about_path, class: 'link-to-text-color-aside' %><%= link_to "Contact - ", contact_path, class: 'link-to-text-color-aside' %>
        <%= link_to "News - ", src="https://instagram.com", class: 'link-to-text-color-aside' %>
        <%= link_to "Instagram Main ", src="https://instagram.com", class: 'link-to-text-color-aside' %>
          <p class="info">clone by Sriram Kaluva</p>
      </section>
    </aside>


  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to the Instaclone App</h1>

    <h2>
      This is the home page for the
      <a href="http://instagram.com/">Instagram</a>'s clone called
      Instaclone application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  </div>

  <%= link_to image_tag("logo.png", alt: "Rails", style: "display: block; margin-left: auto; margin-right: auto; width:100px; height:100px"), 'http://instagram.com/' %>
<% end %>

app/views/static_pages/profilepic.html.erb
<h1>test</h1>

<%= form_for(@profilepic) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="imguploader">
    <%= f.file_field :image, value: "Choose a file", direct_upload: true %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>