config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  resources :microposts do
    member do
      get "like" => "microposts#vote" , :defaults => { :format => 'js' }
      get "delete" => "microposts#destroy"
      get "current" => "microposts#show"
    end
    resources :comments, module: :microposts
  end
  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                          as: :link_through
  resources :conversations do
    member do
      get "convo" => "conversations#create"
    end
    resources :messages
  end
  resources :favorite_microposts do
    member do
      get "fav" => "favorite_microposts#create"
      # get "favs" => "favorite_microposts#index"
      get "unfav" => "favorite_microposts#destroy"
    end
    # resources :messages
  end
  get '/favorites', to: 'favorite_microposts#index', as: 'favorites'
  # resources :favorite_microposts, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :post, only: [:create, :destroy]
  resources :microposts, only: [:create, :show, :destroy]
  resources :profilepics, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  get '/search' => 'users#search', :as => 'search_page'
  # match '/microposts/:id', to: 'microposts#destroy', via: 'get'
  # match '/microposts/:id', to: 'microposts#destroy', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/profilepics', to: 'static_pages#profilepic', via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/microposts/:id/like', to: 'microposts#vote', via: 'get', xhr: true



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id",
                                  class_name:  "Relationship",
                                  dependent:   :destroy
 has_many :followers, through: :reverse_relationships, source: :follower
  has_many :followed_users, through: :relationships, source: :followed
  has_many :microposts, dependent: :destroy
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_one_attached :dp
  has_many :notifications, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :conversations, :foreign_key => :sender_id

  has_many :favorites
  has_many :favorite_microposts, through: :favorites, source: :favorited, source_type: 'Micropost'

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.from_users_followed_by(self)
  end
  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end
  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  def new
    @user = User.new
  end
  def index
    @users = User.paginate(page: params[:page])
  end
  def search
    if params[:search].blank?
    redirect_to(root_path, alert: "Empty field!") and return
  else
    @parameter = params[:search].downcase
    @results = User.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
  end
  end
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])

  end
  def create
    @user = User.new(user_params)
    if @user.save
      # UserMailer.with(user: @user).welcome_email.deliver_now
      sign_in @user
      flash[:success] = "Welcome to the Instaclone!"
      redirect_to @user
    else
      render 'new'
    end

    # respond_to do |format|
    #   if @user.save
    #     # Tell the UserMailer to send a welcome email after save
    #     UserMailer.with(user: @user).welcome_email.deliver_later
    #
    #     format.html { redirect_to(@user, notice: 'User was successfully created.') }
    #     format.json { render json: @user, status: :created, location: @user }
    #   else
    #     format.html { render action: 'new' }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end

  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end
  def following
      @title = "Following"
      @user = User.find(params[:id])
      @users = @user.followed_users.paginate(page: params[:page])
      render 'show_follow'
    end

    def followers
      @title = "Followers"
      @user = User.find(params[:id])
      @users = @user.followers.paginate(page: params[:page])
      render 'show_follow'
    end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation, :bio)
    end
    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    # if gravatar_id.blank?
      gravatar_url = "https://www.gravatar.com/avatar/00000000000000000000000000000000?d=https://cdn1.vectorstock.com/i/thumb-large/82/55/anonymous-user-circle-icon-vector-18958255.jpg"
    # else
    #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    # end

    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id),
             remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </div>
  <%= f.submit "Follow", class: "button" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <div>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </div>
  <%= f.submit "Unfollow", class: "button" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user, class: 'link-to-text-color' %>
  
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" }, class: 'link-to-text-color' %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :bio %>
      <%= f.text_field :bio %>

      <%= f.submit "Save changes", class: "button" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.html.erb
<h3>Search Result</h3>

    <ul class="users">
      <% @results.each do |result| %>
        <li>
          <%= gravatar_for result %>
          <%= link_to result.name, result %>
          <div>
              <%= pluralize(result.microposts.count, "Post") %>
          </div>
          <div>
              <%= link_to "View Profile", result %>
          </div>
        </li>

      <% end %>
    </ul>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="column1">
    <div class="wrapper"> <%= gravatar_for @user %>
    </div>
  </div>
  <div class="column2">
    <ul>
      <div class="user-wrapper">
        <h2 class="username"><%=@user.name%></h2>
        <%= render 'follow_form' if signed_in? %>
      </div>
      <ul class="posts-1">
        <li><span><%= @user.microposts.count %></span> posts</li>
        <li><span><%= @user.followers.count %></span> followers</li>
        <li><span><%= @user.followed_users.count %></span> following</li>
      </ul>
      <% if @user.bio.nil? || @user.bio == '' || @user.bio == ' ' %>
      <div class="bio">
        <p class="bio-p">Hey! This is "<%=@user.name%>". This is my instaclone account. Follow me to know about me!!</p>
      </div>
      <% else %>
      <div class="bio">
        <p class="bio-p"><%= @user.bio %></p>
      </div>
      <% end %>
      <% if current_user?@user %>
      <div class="edit-bio">
        <%= link_to '<i class="gg-edit-markup"></i>'.html_safe, edit_user_path(current_user), class: 'link-to-text-color' %>
      </div>
      <div class="saved">
        <%= link_to '<i class="gg-bookmark"></i>'.html_safe, favorites_path, class: 'link-to-text-color' %>
      </div>
      <% end %>
    </ul>
</div>
</div>

<hr class="hr-line">
<div class="row">
  <div class="column3">
    <% if @user.microposts.any? %>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
      <% end %>
    </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Posts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>