config/routes.rb
Rails.application.routes.draw do
  get 'notifications/link_through'
  resources :microposts do
    member do
      get "like" => "microposts#vote" , :defaults => { :format => 'js' }
      get "delete" => "microposts#destroy"
      get "current" => "microposts#show"
    end
    resources :comments, module: :microposts
  end
  resources :users do
    member do
      get :following, :followers
    end
  end

  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                          as: :link_through
  resources :conversations do
    member do
      get "convo" => "conversations#create"
    end
    resources :messages
  end
  resources :favorite_microposts do
    member do
      get "fav" => "favorite_microposts#create"
      # get "favs" => "favorite_microposts#index"
      get "unfav" => "favorite_microposts#destroy"
    end
    # resources :messages
  end
  get '/favorites', to: 'favorite_microposts#index', as: 'favorites'
  # resources :favorite_microposts, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  resources :post, only: [:create, :destroy]
  resources :microposts, only: [:create, :show, :destroy]
  resources :profilepics, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root  'static_pages#home'
  get '/search' => 'users#search', :as => 'search_page'
  # match '/microposts/:id', to: 'microposts#destroy', via: 'get'
  # match '/microposts/:id', to: 'microposts#destroy', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/profilepics', to: 'static_pages#profilepic', via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  match '/microposts/:id/like', to: 'microposts#vote', via: 'get', xhr: true



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <div class="post-title">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span>
      <%= link_to feed_item.user.name, feed_item.user, class: 'link-to-text-color' %>
    </span>

    <% if current_user?(feed_item.user) %>
    <span class="dropdown">
        <a href="javascript:void(0)" class="dropbtn"><i class="gg-options"></i></a>

        <div class="dropdown-content">

          <% if current_user?(feed_item.user) %>
            <%= link_to "Delete", delete_micropost_path(feed_item), method: :delete,
                                             data: { confirm: "You sure?" },
                                             title: feed_item.image, class: 'link-to-text-color' %>
          <% end %>
        </div>
      </span>
      <% end %>
  </div>
  <br>
  <div>
    <%= link_to current_micropost_path(feed_item.id) do %>
    <span class="img"><%= image_tag(feed_item.image) %></span>
    <% end %>
    <%= link_to like_micropost_path(feed_item), class: "like-btn", method: :put,remote: :true do %>
    <div>
      <% if current_user.liked? feed_item %>
        <span><p><i class="gg-heart-liked"></i></p> </span>
        <% else %>
        <span><p><i class="gg-heart"></i></p></span>
      <% end %>
      <span>
        <%- unless current_user.favorite_microposts.exists?(id: feed_item.id) -%>
          <%= link_to '<i class="gg-bookmark"></i>'.html_safe, fav_favorite_micropost_path(id: feed_item.id), method: :get, class: 'bookmark' %>
        <%- else -%>
          <%= link_to '<i class="gg-bookmark-added"></i>'.html_safe, unfav_favorite_micropost_path(id: feed_item.id), method: :delete, class: 'bookmark' %>
        <%- end -%>
      </span>
    </div>
    <% end %>

      <p class="heart"><%= pluralize(feed_item.get_upvotes.size, 'like') %></p>

      <span class="content"><%= link_to feed_item.user.name, feed_item.user, class: 'username-for-description' %>  <%= feed_item.caption %></span>
<!-- <hr> -->
    <div class= "comments">
      <% if !feed_item.comments.blank? %>
      <!-- <p class="comments-logo"><i class="gg-comment"></i></p> -->
      <!-- <p>Comments</p> -->

        <% feed_item.comments.each do |comment| %>
          <div class="comments-well">
            <span class="comments-name"><%= link_to User.find(comment.user_id).name, User.find(comment.user_id), class: 'username-for-description' %></span>  <span><%= comment.body %></span>
          <span class="comments-time"><%= time_ago_in_words(comment.created_at) %></span>
          </div>
          <% end %>
      <% end %>
    </div>


    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
    <!-- <hr> -->
    <div class="comments">
      <%= form_for [feed_item, Comment.new] do |f| %>
      <div class="form-group">
        <%= f.text_field :body, class: "form-control-comments", placeholder: "Add your Comment", id:feed_item.id %>
      </div>
      <% end %>
    </div>



  </div>
</li>

app/views/shared/_micropost_form.html.erb
<script type="text/javascript">
  function openNav() {
  document.getElementById("myNav").style.width = "100%";
}

/* Close when someone clicks on the "x" symbol inside the overlay */
function closeNav() {
  document.getElementById("myNav").style.width = "0%";
}
</script>
<div id="myNav" class="overlay">
<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

<div class="overlay-content">
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.file_field :image, value: "Choose a file", direct_upload: true %>
    <div class="overlaytextarea">
        <%= f.text_area :caption, placeholder: "Caption/Describe your post here..." %>
    </div>
  <%= f.submit "Post", class: "button button1" %>
<% end %>
</div>
</div>
<span onclick="openNav()"><i class="gg-add-r"></i></span>

app/views/shared/_profile_feed_item.html.erb
<li>
  <%= image_tag (profile_feed_item.image) %>
  <span class="user">
    <%= link_to profile_feed_item.user.name, profile_feed_item.user %>
  </span>
</li>

app/views/shared/_profilepic.html.erb
<%= image_tag(current_user.profilepic.image) %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
</div>

app/views/shared/_stats_home.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    Following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    Followers
  </a>
  </div>

app/views/shared/_suggested_users.html.erb
<ul class="suggestions">
  <div class="row">
    <div class="column4">
        Suggestions For You
    </div>

    <div class="column5">
        <%= link_to "See all", users_path, class: 'link-to-text-color' %>
    </div>
  </div>

</ul>
<ul class="suggested-users">
  <% following = Array.new %>
  <% not_following = Array.new %>
  <% @users.each do |user| %>
    <% if current_user.following?(user) %>
      <% following << user %>
    <% else %>
      <% not_following << user %>
    <% end %>
  <% end %>
  <% arr = not_following.sample(5)%>
  <% arr.each do |user| %>
    <li>
      <%= gravatar_for user %>
      <%= link_to user.name, user, class: 'link-to-text-color' %>
      <%= link_to "See Profile", user, class: 'link-to-text-color',style: "float: right" %>
      <span><%= pluralize(user.microposts.count, "Post") %>
      </span>
    </li>
  <% end %>
</ul>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<span>&nbsp;</span>
<span>
  <h1><%= link_to current_user.name, current_user, class: 'link-to-text-color' %></h1>
</span>
<span class="userinfo-saved"><%= link_to '<i class="gg-bookmark"></i>'.html_safe, favorites_path %></span>